"""Initial migration

Revision ID: 00ae50fab798
Revises: 
Create Date: 2024-08-24 12:52:33.105415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00ae50fab798'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('level_code', sa.String(length=10), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_table('topic',
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('AIQuestion', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickName', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('socialLogin', sa.Boolean(), nullable=True),
    sa.Column('withdrawal', sa.Boolean(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ai_chat',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatDate', sa.Date(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('pronunciation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('ai_chat_test',
    sa.Column('chatTest_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatDate', sa.Date(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('grammar', sa.Float(), nullable=True),
    sa.Column('vocabulary', sa.Float(), nullable=True),
    sa.Column('content', sa.Float(), nullable=True),
    sa.Column('simpleEvaluation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chatTest_id')
    )
    op.create_table('social_login',
    sa.Column('socialLogin_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('socialLoginCode', sa.String(length=255), nullable=False),
    sa.Column('socialLoginId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('socialLogin_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('teamName', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('user_character',
    sa.Column('user_character_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('character_id', sa.String(length=36), nullable=False),
    sa.Column('selected_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.character_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_character_id')
    )
    op.create_table('user_level',
    sa.Column('user_level_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('level_code', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_level_id')
    )
    op.create_table('ai_chat_test_content',
    sa.Column('chatTestContent_id', sa.String(length=36), nullable=False),
    sa.Column('chatTest_id', sa.String(length=36), nullable=False),
    sa.Column('chatDate', sa.DateTime(), nullable=False),
    sa.Column('userContent', sa.Text(), nullable=False),
    sa.Column('AIContent', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chatTest_id'], ['ai_chat_test.chatTest_id'], ),
    sa.PrimaryKeyConstraint('chatTestContent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_chat_test_content')
    op.drop_table('user_level')
    op.drop_table('user_character')
    op.drop_table('team')
    op.drop_table('social_login')
    op.drop_table('ai_chat_test')
    op.drop_table('ai_chat')
    op.drop_table('user')
    op.drop_table('topic')
    op.drop_table('character')
    # ### end Alembic commands ###
