"""Initial migration

Revision ID: c18d5b015a46
Revises: 
Create Date: 2024-08-09 17:14:15.202417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18d5b015a46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('AIQuestion', sa.Text(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('userName', sa.String(length=255), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('socialLogin', sa.Boolean(), nullable=True),
    sa.Column('withdrawal', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('ai_chat',
    sa.Column('chat_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatDate', sa.Date(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('pronunciation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('ai_chat_test',
    sa.Column('chatTest_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('chatDate', sa.Date(), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('grammar', sa.Float(), nullable=True),
    sa.Column('vocabulary', sa.Float(), nullable=True),
    sa.Column('content', sa.Float(), nullable=True),
    sa.Column('simpleEvaluation', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.topic_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('chatTest_id')
    )
    op.create_table('social_login',
    sa.Column('socialLogin_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('socialLoginCode', sa.String(length=255), nullable=False),
    sa.Column('socialLoginId', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('socialLogin_id')
    )
    op.create_table('team',
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('teamName', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('team_id')
    )
    op.create_table('ai_chat_test_content',
    sa.Column('chatTestContent_id', sa.String(length=36), nullable=False),
    sa.Column('chatTest_id', sa.String(length=36), nullable=False),
    sa.Column('chatDate', sa.DateTime(), nullable=False),
    sa.Column('userContent', sa.Text(), nullable=False),
    sa.Column('AIContent', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['chatTest_id'], ['ai_chat_test.chatTest_id'], ),
    sa.PrimaryKeyConstraint('chatTestContent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_chat_test_content')
    op.drop_table('team')
    op.drop_table('social_login')
    op.drop_table('ai_chat_test')
    op.drop_table('ai_chat')
    op.drop_table('user')
    op.drop_table('topic')
    # ### end Alembic commands ###
